version: '3.9'

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=rwurdig
      - MYSQL_PASSWORD=1234
    ports:
      - '3336:3306'
    expose:
      - '3336'
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
    networks:
      sicooperative-net:
        ipv4_address: 172.20.0.10
  spark:
    container_name: spark-master
    image: docker.io/bitnami/spark:3
    depends_on:
     - db
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '9090:8080'
      - '7077:7077'
    volumes:
      - './runner.py:/opt/bitnami/spark/jobs/runner.py'
      - './jars/mysql-connector.jar:/opt/bitnami/spark/jars/mysql-connector.jar'
    networks:
      sicooperative-net:
        ipv4_address: 172.20.0.11
  spark-worker-a:
    container_name: spark-worker-a
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - './runner.py:/opt/bitnami/spark/jobs/runner.py'
      - './jars/mysql-connector.jar:/opt/bitnami/spark/jars/mysql-connector.jar'
    depends_on:
      - spark
    networks:
      sicooperative-net:
        ipv4_address: 172.20.0.12

networks:
  sicooperative-net:
    ipam:
      config:
        - subnet: 172.20.0.0/16